site_name: Aircraft Design
repo_url: https://github.com/NisusAerodesign/aircraft-design
repo_name: Nisus/aircraft-design
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/airplane.png
  favicon: assets/airplane.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css